# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatroom.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_SafeChatroom(object):
    def setupUi(self, SafeChatroom):
        SafeChatroom.setObjectName("SafeChatroom")
        SafeChatroom.resize(404, 546)
        SafeChatroom.setMinimumSize(QtCore.QSize(404, 175))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        SafeChatroom.setFont(font)
        SafeChatroom.setAutoFillBackground(False)
        self.gridLayout = QtWidgets.QGridLayout(SafeChatroom)
        self.gridLayout.setObjectName("gridLayout")
        self.send = QtWidgets.QPushButton(SafeChatroom)
        self.send.setObjectName("send")
        self.gridLayout.addWidget(self.send, 1, 2, 1, 1)
        self.recv_window = QtWidgets.QTextBrowser(SafeChatroom)
        self.recv_window.setObjectName("recv_window")
        self.gridLayout.addWidget(self.recv_window, 0, 0, 1, 3)
        self.historySaver = QtWidgets.QPushButton(SafeChatroom)
        self.historySaver.setObjectName("historySaver")
        self.gridLayout.addWidget(self.historySaver, 1, 0, 1, 1)
        self.nickname_changer = QtWidgets.QPushButton(SafeChatroom)
        self.nickname_changer.setObjectName("nickname_changer")
        self.gridLayout.addWidget(self.nickname_changer, 1, 1, 1, 1)
        self.send_window = QtWidgets.QLineEdit(SafeChatroom)
        self.send_window.setAutoFillBackground(False)
        self.send_window.setObjectName("send_window")
        self.gridLayout.addWidget(self.send_window, 2, 0, 1, 3)

        self.retranslateUi(SafeChatroom)
        QtCore.QMetaObject.connectSlotsByName(SafeChatroom)

    def retranslateUi(self, SafeChatroom):
        _translate = QtCore.QCoreApplication.translate
        SafeChatroom.setWindowTitle(_translate("SafeChatroom", "SafeChatroom"))
        SafeChatroom.setWhatsThis(_translate("SafeChatroom", "<html><head/><body><p>test</p></body></html>"))
        SafeChatroom.setWindowIcon(QIcon("./img/icon.png"))
        self.send.setText(_translate("SafeChatroom", "Send"))
        self.historySaver.setText(_translate("SafeChatroom", "Save Chat History"))
        self.nickname_changer.setText(_translate("SafeChatroom", "Change Nickname"))
