# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popout.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_popout(object):
    def setupUi(self, popout):
        popout.setObjectName("popout")
        popout.resize(400, 400)
        popout.setMinimumSize(QtCore.QSize(400, 400))
        popout.setMaximumSize(QtCore.QSize(400, 400))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        popout.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(popout)
        self.gridLayout.setObjectName("gridLayout")
        self.IPAddress = QtWidgets.QLineEdit(popout)
        self.IPAddress.setObjectName("IPAddress")
        self.gridLayout.addWidget(self.IPAddress, 1, 0, 1, 1)
        self.submit = QtWidgets.QPushButton(popout)
        self.submit.setObjectName("submit")
        self.gridLayout.addWidget(self.submit, 3, 0, 1, 1)
        self.info = QtWidgets.QTextBrowser(popout)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.info.setFont(font)
        self.info.setObjectName("info")
        self.gridLayout.addWidget(self.info, 0, 0, 1, 1)
        self.port = QtWidgets.QLineEdit(popout)
        self.port.setObjectName("port")
        self.gridLayout.addWidget(self.port, 2, 0, 1, 1)

        self.retranslateUi(popout)
        QtCore.QMetaObject.connectSlotsByName(popout)

    def retranslateUi(self, popout):
        _translate = QtCore.QCoreApplication.translate
        popout.setWindowTitle(_translate("popout", "Welcome"))
        self.IPAddress.setText(_translate("popout", "IP address here..."))
        self.submit.setText(_translate("popout", "Submit"))
        self.info.setHtml(_translate("popout", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\',\'Consolas\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">Welcome to SafeChatroom 2.0.1 developed by </span><span style=\" font-family:\'SimSun\'; font-size:10pt; color:#0000ff;\">杨博文</span><span style=\" font-family:\'SimSun\'; font-size:10pt;\">. The software uses RSA and AES to realize end-to-end communication with mixed encryption. Source codes can be found at </span><span style=\" font-family:\'SimSun\'; font-size:10pt; font-style:italic;\">https://github.com/debidong/Safechatroom</span><span style=\" font-family:\'SimSun\'; font-size:10pt;\">.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">In order to connect to the server, please enter the working port number and IP address of server. They are also set and can be changed in </span><span style=\" font-family:\'SimSun\'; font-size:10pt; font-style:italic;\">./lib/ipconfig.json</span><span style=\" font-family:\'SimSun\'; font-size:10pt;\">.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">The form of IP address should look like:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">127.0.0.1</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">The form of port number should look like:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">8000</span></p></body></html>"))
        self.port.setText(_translate("popout", "Port number here..."))
